# serverless.yml
#
# it is expected that depoendencies in README.md will be fulfilled
# crib sheet is here: https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
#
#upload lambda appliction:     $ serverless deploy
#

service: imf-mm-api-server

provider:
  name: aws
  runtime: nodejs8.10
  stage: staging
  region: us-east-2
  
  profile: api                #use aws credentials from the api profile
  memorySize: 1024            #default memory size
  timeout: 30                 #default is 6 seconds
  environmentVariables:       #service wide Environment
    NODE_ENV: staging

functions:
  app:                       #function name
    handler: src/start_awslambda.handler
    events:
      - http: 'ANY {proxy+}'
